AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PySpark Lambda using Docker

Resources:
  PySparkLambdaFunction:
    Type: AWS::Serverless::Function
    Name: "text-processor-app"
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
